version: '3.5'
services:
  web:
    restart: always
    build: ./web
    expose:
      - "8000"
    volumes:
      - /usr/src/app/web/project/static
    command: /usr/local/bin/gunicorn -w 2 -b :8000 project:app
    depends_on:
      - postgres
    environment:
      POSTGRES_DB: 
      POSTGRES_USER: 
      POSTGRES_PASSWORD: 
      POSTGRES_PORT: 5432

  nginx:
    restart: always
    build: ./nginx
    ports:
      - "80:80"
    volumes:
      - /www/static
    depends_on:
      - web
      
  postgres:
    restart: always
    image: postgres:latest
    volumes:
      - db_volume:/var/lib/postgresql
    expose:
      - "5432"
    environment:
      POSTGRES_DB: 
      POSTGRES_USER: 
      POSTGRES_PASSWORD: 
      POSTGRES_PORT: 5432
volumes:
  db_volume: